# Generated by Django 4.2 on 2023-06-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptran_sdate', models.DateTimeField()),
                ('msisdn', models.CharField(max_length=15)),
                ('bill_no', models.CharField(max_length=20)),
                ('bill_disc', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('trans_code', models.CharField(max_length=10)),
                ('trans_id', models.CharField(max_length=20)),
                ('trans_status', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
