# Generated by Django 4.2 on 2023-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
