# Generated by Django 4.2 on 2023-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agservice', '0002_alter_payload_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='trans_id',
            new_name='client_trans_id',
        ),
        migrations.AddField(
            model_name='payload',
            name='tugw_trans_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
