# Generated by Django 4.2 on 2023-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agservice', '0003_rename_trans_id_payload_client_trans_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='mcom_desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payload',
            name='mcom_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payload',
            name='mcom_status',
            field=models.CharField(default='', max_length=2),
        ),
    ]
