# Generated by Django 4.2 on 2023-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agservice', '0004_payload_mcom_desc_payload_mcom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='client_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
